name: mad_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cloud_firestore: ^6.0.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  provider: ^6.1.2
  fl_chart: ^1.1.0
  intl: ^0.20.1
  # shared_preferences: ^2.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2


flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/jsonData/
